package info.rsdev.mysite.common;

import java.util.Properties;

/**
 * The constants for the property keys that are generated by the site for every module 
 */
public interface DefaultConfigKeys {
    
    /**
     * The filesystem directory outside the webapp that can be used by the website for storage that survives
     * upgrades and reboots. It is generated when te ModuleConfig is loaded.
     */
    public static final String SITE_DATA_DIR_KEY = "SiteDataDir";
    
    public static final String CONTEXTPATH_KEY = "servletContextPath";
    /**
     * The mountpoint on which the module is mounted. This property is generated when the ModuleConfig is loaded.
     */
    public static final String MOUNTPOINT_KEY = "MountPoint";
    
    /**
     * The logical name of the site. This is not an alias and does not need to be an actual fully qualified hostname.
     * This property is generated when the ModuleConfig is loaded.
     */
    public static final String SITENAME_KEY = "SiteName";
    
    /**
     * The fully qualified name of the Java class that implements the {@link ModuleConfig} interface for this module. It must
     * have a public constructor that accepts a {@link Properties} argument. It must be set in the module's configuration
     * properties.
     */
    public static final String MODULECONFIGTYPE_KEY = "ModuleConfigType";
    
    public static final String TEMPLATE_NAME_KEY = "template";
    
    public static final String CUSTOM_TEMPLATE_FOLDER_KEY = "customTemplateFolder";
    
    /**
     * The path relative to the site data directory that is the root directory for this image collection
     */
    public static final String COLLECTION_PATH_KEY = "collection";
    /**
     * The list of menuitem names, separated by a column (:), that may appear in the navigation menu, in the order
     * that they will appear. This is a filter and it is applied to a list of menu items; it will not cause menu items
     * to be created, it only removes ones that are not wanted and orders the remaining ones.
     */
    public static final String APPROVED_MENUITEMS_KEY = "menuitems";
    
    public static final String MENU_ORDER_PRIORITY_KEY = "menuSortingPriority";
    
    public static final int DEFAULT_MENU_ORDER_PRIORITY_VALUE = 1000;
    
    public static final String MENUGROUP_TITLE_KEY = "menugroupTitle";
    
    public static final String CSS_LOCATION_KEY = "stylesheetlocation";
    
    public static final String COPYRIGHT_NOTICE_KEY = "copyrightnotice";
    
    public static final String DISABLED_KEY = "disabled";
    
    public static final String LOCALE_KEY = "locale";
    
}