= General

== Introduction

  Explain that it's build on top of:
  - bootstrap
  - stringtemplate


== Configuration

Some configuration recur in every module. Instead of describing them with every module, they are described here. However, they 
should be configured in every module's property file.

The following properties are identified as the 'set of general properties':

|===
| property name                 | Description
| stylesheetlocation             | The location of bootstrap. When not specified, the default bootstrap 
configuration is loaded from internet.
| copyrightnotice               | A short text, preferably on a single line, indicating the copyright 
holder to the content of the website.
| menugroupTitle                | The title of the menu group. Can be rendered by the page template 
or not, depending on the template
| menuitems                     | List with imagegroup names that must be visible in the navigation menu,
 in the given order. List items are separated with a column (:) \
| menuSortingPriority           | Integer value, indicating the order of the menugroup to be displayed 
in the menu. The lower the number, the higher it will appear in the menu.
| ModuleConfigType              | The fully qualified java class name that must handle the module's 
configuration. The implementation supplied by MySite is info.rsdev.mysite.gallery.GalleryModuleConfig
| template                      | The name of the default GUI template that must be used to show the 
content, when there is none provided for a specific menuitem (see below).
| <menuItemName>.template       | The name of the GUI template that must be used to show the content 
behind a specific menuitem. When none provided, the default template is used (see above).
| disabled                      | A boolean value, and when true, shows an 'unavailable' page, and when 
false, shows the regular content 
| customTemplateFolder          | The path to a folder inside the website data directory where custom templates are
located. Currently only stringtemplate group files are supported. This is an alternative to locating the template in the
root of the folder containing the collection of resources served by the module.
| locale                        | The language code for the content served by this module. If none provided, the Java platform default Locale is used 
|===

== Global configuration

Some properties are the same for every module. To prevent repeating yourself there is a mechanism to configure them globally and they
will be picked up by every module. If you configure a property on both global level and module level, the value set on module level wins.

Properties that lend themselves for configuration on global level are e.g. the copyrightnotice, stylesheetlocation,
customTemplateFolder and disabled.

The global configuration is located in the file named .properties in the root folder of the websites data directory.
