package info.rsdev.mysite.common;

import java.util.Properties;

/**
 * The constants for the property keys that are generated by the site for every module 
 */
public interface DefaultConfigKeys {
    
    public static final String SITE_DATA_DIR_KEY = "SiteDataDir";
    
    /**
     * The mountpoint on which the module is mounted. This property is generated when the ModuleConfig is loaded.
     */
    public static final String MOUNTPOINT_KEY = "MountPoint";
    
    /**
     * The logical name of the site. This is not an alias and does not need to be an actual fully qualified hostname.
     */
    public static final String SITENAME_KEY = "SiteName";
    
    /**
     * The fully qualified name of the Java class that implements the {@link ModuleConfig} interface form this module. It must
     * have a public constructor that accepts a {@link Properties} argument.
     */
    public static final String MODULECONFIGTYPE_KEY = "ModuleConfigType";
}